# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nav_message.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11nav_message.proto\x12\x08gnss_sdr\"l\n\x06navMsg\x12\x0e\n\x06system\x18\x01 \x01(\t\x12\x0e\n\x06signal\x18\x02 \x01(\t\x12\x0b\n\x03prn\x18\x03 \x01(\x05\x12 \n\x18tow_at_current_symbol_ms\x18\x04 \x01(\x05\x12\x13\n\x0bnav_message\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nav_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NAVMSG']._serialized_start=31
  _globals['_NAVMSG']._serialized_end=139
# @@protoc_insertion_point(module_scope)
